title: AgWise RTD
description: Port of Rad-the-docs for AgWise DST for Excellence in Agronomy.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Eduardo Garcia Bendito
repo_url: 'https://github.com/egbendito/mashawara'
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
