title: AgWise RTD
description: Port of Rad-the-docs for AgWise DST for Excellence in Agronomy.
remote_theme: egbendito/jekyll-theme-rtd

# Theme settings:
site_author: Eduardo Garcia Bendito
repo_url: "https://github.com/egbendito/mashawara"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
